parameters:
    coderGeekMaintenanceListener: CoderGeek\Bundle\MaintenanceBundle\Listener\MaintenanceListener
    coderGeekMaintenanceDriverFactory: CoderGeek\Bundle\MaintenanceBundle\Drivers\DriverFactory

services:
    codergeek_maintenance.driver.factory:
        class: %coderGeekMaintenanceDriverFactory%
        arguments: ['%codergeek_maintenance.driver%']
    codergeek_maintenance.listener:
        class: %coderGeekMaintenanceListener%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        arguments: ['@codergeek_maintenance.driver.factory','%codergeek_maintenance.maintenance.template%','%codergeek_maintenance.whitelist.ips%','%codergeek_maintenance.whitelist.route%','%codergeek_maintenance.response.http_code%','%codergeek_maintenance.response.http_status%']
